### PR TITLE
fix: extend/duplicate .widget-title and .accent-header styles (#1470)

### LINKED ISSUE #1470: Legacy widget title classes getting changed when nested in a Group block
When you nest a legacy widget inside of a group block, the widget title's class changes from `.widget-title` to `.widgettitle`.

Edited to add: it also looks like it's stripping out the `.accent-header` class that [the theme adds to the sidebar widgets](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/functions.php#L292).

This has already been reported in [the Gutenberg repo](https://github.com/WordPress/gutenberg/issues/33507), but to avoid visual issues in the short-term, I think we should 'duplicate' the `.widget-title` styles so they're also applied to this alternative class; it can be removed once this is fixed in WordPress.

### PR DESCRIPTION
**Pull request by 9ete**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #1470

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1200734123818559

### CODE REVIEW

File: newspack-nelson/inc/child-typography.php [hunk 1]
```diff
@@ -37,20 +37,21 @@ function newspack_nelson_custom_typography_css() {
 			.nav3,
 			.mobile-menu-toggle,
 			.accent-header,
+			.widgettitle,
```
Comment (laurelfulford) [inline newspack-nelson/inc/child-typography.php:40]: This should target the sidebar specifically, like: 

```suggestion
			#secondary .widgettitle,
```

... since the uppercase styles are not applied to widget areas like the slide-out sidebar, or when widgets appear in the mobile menu.

File: newspack-nelson/sass/style-editor.scss [hunk 2]
```diff
@@ -25,6 +25,7 @@ blockquote {
 // Accent Headers
 
 .accent-header,
+.widgettitle,
```
Comment (laurelfulford) [inline newspack-nelson/sass/style-editor.scss:28]: The `.widgettitle` shouldn't be needed here, because the class shouldn't appear in the block editor: 

```suggestion
```

File: newspack-nelson/sass/style.scss [hunk 3]
```diff
@@ -262,6 +262,7 @@ h4,
 // Accent headers
 
 .accent-header,
+.widgettitle,
```
Comment (laurelfulford) [inline newspack-nelson/sass/style.scss:265]: These specific styles are only needed on the `.widgettitle` class in the sidebar:

```suggestion
#secondary .widgettitle,
```

File: newspack-sacha/inc/child-typography.php [hunk 4]
```diff
@@ -42,6 +42,7 @@ function newspack_sacha_custom_typography_css() {
 	if ( true === get_theme_mod( 'accent_allcaps', true ) ) {
 		$css_blocks        .= '
 			.accent-header,
+			.widgettitle,
```
Comment (laurelfulford) [inline newspack-sacha/inc/child-typography.php:45]: This should just be applied to when the `.widgettitle` class appears in the sidebar:

```suggestion
			#secondary .widgettitle,
```

File: newspack-sacha/sass/style.scss [hunk 5]
```diff
@@ -72,12 +72,14 @@ Nicolas Gallagher and Jonathan Neal https://necolas.github.io/normalize.css/
 
 // Accent headers
 .accent-header,
+.widgettitle,
```
Comment (laurelfulford) [inline newspack-sacha/sass/style.scss:75]: This should just apply when the `.widgettitle` class appears in the sidebar:

```suggestion
#secondary .widgettitle,
```

File: newspack-sacha/sass/style.scss [hunk 6]
```diff
@@ -86,6 +88,7 @@ div.wpnbha .article-section-title,
 }
 
 .accent-header,
+.widgettitle,
```
Comment (laurelfulford) [inline newspack-sacha/sass/style.scss:91]: The borders should just be applied to the `.widgettitle` class when it appears in the sidebar:

```suggestion
#secondary .widgettitle,
```

**Review by laurelfulford — CHANGES_REQUESTED** [review]
Thanks so much again for your hard work on this PR, @9ete!

We're well into the silly nitpicky weeds with this feedback -- I just found some cases weren't quite acting right, but a ton of the original feedack has been addressed. For the most part I included the feedback in comments directly in the code, but included a bit more below to address an issue that needs to be tweaked in files that haven't been changed yet.

If you have any questions at all about any of this, please let me know!

**For Newspack Katharine:**

The sidebar `.widgettitle` isn't picking up the correct styles -- editing these files should fix!

image


newspack-katharine/inc/child-color-patterns.php
*  `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L35-L45
* `#secondary .widgettitle::before` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L53-L61

newspack-katharine/inc/child-color-typography.php
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-typography.php#L33-L43

newspack-katharine/sass/style.scss
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/sass/style.scss#L51-L65

**Comment by 9ete** [comment]
@laurelfulford all issues resolved, ready for re-review.

File: newspack-sacha/inc/child-color-patterns.php [hunk 7]
```diff
@@ -38,10 +38,12 @@ function newspack_sacha_custom_colors_css() {
 		.entry-meta .byline a:visited,
 		.entry .entry-meta a:hover,
 		.accent-header,
+		.widgettitle,
```
Comment (laurelfulford) [inline newspack-sacha/inc/child-color-patterns.php:41]: This should be targeted to the sidebar (as well as the footer below) so it's not picked up by any other widget spaces:
```suggestion
		#secondary .widgettitle,
```

File: newspack-sacha/sass/style.scss [hunk 8]
```diff
@@ -72,12 +72,14 @@ Nicolas Gallagher and Jonathan Neal https://necolas.github.io/normalize.css/
...
 // Accent headers
 .accent-header,
+#secondary .widgettitle,
 .article-section-title,
 .cat-links {
 	color: $color__primary;
 }
 
 .accent-header,
+#secondary .widgettitle,
```
Comment (laurelfulford) [inline newspack-sacha/sass/style.scss:82]: Currently the styles in this section (starting at line 73) look like:
```
// Accent headers
.accent-header,
#secondary .widgettitle,
.article-section-title,
.cat-links {
	color: $color__primary;
}

.accent-header,
#secondary .widgettitle,
div.wpnbha .article-section-title,
.cat-links {
	font-size: $font__size-xs;
	margin-bottom: $size__spacing-unit;
	text-align: center;
}
```

They way we broke them up isn't exactly necessary, and the `$font__size-xs;` is making the sidebar widget titles extra small: 

image

Rejigging the current styles a bit should help fix the font sizing -- below I combined all four selectors to apply the colour, margin and text-alignment, and then removed `#secondary .widgettitle` where the font size has been applied: 


```
.accent-header,
#secondary .widgettitle,
.article-section-title,
.cat-links {
	color: $color__primary;
	margin-bottom: $size__spacing-unit;
	text-align: center;
}

.accent-header,
div.wpnbha .article-section-title,
.cat-links {
	font-size: $font__size-xs;
}
```

**Review by laurelfulford — CHANGES_REQUESTED** [review]
Thanks @9ete! It's down to just a couple more things now, some of which I missed the last time through! 

I added some comments in the code, and below -- the changes for Newspack Katharine are copied from the last review, but the changes for Newspack Scott underneath that I missed the last time through -- I think I missed testing it. Apologies! 

Just let me know if you have any questions at all -- thank you!

**For Newspack Katharine:**

The sidebar `.widgettitle` isn't picking up the correct styles -- editing these files should fix!

image


newspack-katharine/inc/child-color-patterns.php
*  `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L35-L45
* `#secondary .widgettitle::before` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L53-L61

newspack-katharine/inc/child-color-typography.php
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-typography.php#L33-L43

newspack-katharine/sass/style.scss
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/sass/style.scss#L51-L65


**For Newspack Scott**

The widget titles aren't quite picking up the correct case in the sidebar, or colour and case in the footer -- the following tweaks should fix! 

image

newspack-scott/inc/child-color-patterns.php
* `#colophon .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-color-patterns.php#L101-L105

newspack-scott/inc/child-typography.php
* `#secondary .widgettitle` and `#colophon .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-typography.php#L39-L46

newspack-scott/sass/style.scss
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/sass/style.scss#L61-L63

**Comment by 9ete** [comment]
@laurelfulford thanks for the feedback, I've addressed all issues, should be good to go now!

File: newspack-nelson/inc/child-typography.php [hunk 9]
```diff
@@ -37,20 +37,21 @@ function newspack_nelson_custom_typography_css() {
...
-			.site-footer .widget-title {
+			.site-footer .widget-title ,
+			.site-footer .widgettitle {
 				letter-spacing: 0.05em;
 				text-transform: uppercase;
 			}
 		';
 		$editor_css_blocks .= '
 			.block-editor-block-list__layout .block-editor-block-list__block.accent-header,
-			.block-editor-block-list__layout .block-editor-block-list__block .article-section-title,
```
Comment (laurelfulford) [inline newspack-nelson/inc/child-typography.php:53]: I think `.block-editor-block-list__layout .block-editor-block-list__block .article-section-title,` here was accidentally removed as part of a formatting fix -- [in a previous run though](https://github.com/Automattic/newspack-theme/pull/1678/files/cc33f078c38a922f8b03dcb5842710e830297930#diff-4f35070fcc5427e4d0f46f3d0a3d8d32a1f6b3ff4a1f308c54e0f56c4ec143c0), I'd commented that a line break had been removed when it shouldn't be between this selector and the one above it, but I think the code comparison I included made it look like the whole bit should be removed! 

If you can please re-add this, I think this PR is ready to go!

**Review by laurelfulford — CHANGES_REQUESTED** [review]
Thank you, @9ete! 

I went through this with a fine toothed comb one more time, and only spotted one issue with a formatting fix that was made earlier on (instead of re-adding a line-break, a bit of code was removed). Other than that, everything looks fantastic! 🎉 

Thank you again for your hard work on this. Once that bit of code is back, this will be ready to merge!

File: newspack-nelson/inc/child-typography.php (hunk 9 above)
Comment (9ete) [reply newspack-nelson/inc/child-typography.php]: @laurelfulford done!

**Review by laurelfulford — APPROVED** [review]
Everything looks good -- thanks again so much for your help and patience with this PR, @9ete! 🎉
