### PR TITLE
fix: update approach to remove space with above footer ad

### LINKED ISSUE #1743: Above footer ad is getting cut off when background colour is set.
**Describe the bug**

Discovered while testing #1742.

The `margin-bottom: -2rem` on the above footer ad space is causing the ad to get cut off -- I suspect it was originally added to close the gap between the ad and the footer.

**To Reproduce**
1. Add an above footer ad to your site.
2. Under Customizer > Colours, enable the Ad background colour.
3. View on front end; note the ad is getting cut off, and the background is not touching the footer.

**Screenshots**

image

**Expected behavior**

That the full ad would display, and that the gap between the background and footer would be gone.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR changes the approach to removing the gap between the above footer ad space when it has a background, and the footer. 

Originally this was done by adding a negative margin to the ad space; I believe that stopped working as expected when the `overflow: hidden` was moved in #1254-- now, the negative margin causes the ad to get cut off. 

This PR checks for an ad in that location, and if there is one, adds a CSS that's then used to remove the margin above the footer. 

This approach seemed the least disruptive (it doesn't try to move the ad; it doesn't remove the margin on top of the footer outright), but I'm open to feedback if it seems like it's over-complicating things. I also may not have used the best approach for checking for the Above Footer ad space!

Closes #1743

### How to test the changes in this Pull Request:

1. Navigate to Customizer > Colors, and add a background colour to your ads.
2. Add an ad to the 'Above Footer' location.
3. View on the front end -- there is a gap between your ad background colour, and part of your ad is getting cut off: 

image

5. Apply the PR and run `npm run build`.
6. Confirm that the ad is no longer cut off, and there is no longer a gap between the ad background and the footer. 

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: newspack-theme/inc/template-functions.php [hunk 1]
```diff
@@ -213,12 +213,17 @@ function newspack_body_classes( $classes ) {
 		$classes[] = 'feature-latest';
 	}
 
-	// Add a class when there's an ad background color.
+	// Add a class when there's an ad background color, and another when there's an ad above the footer to remove the space.
 	$ads_background_color = get_theme_mod( 'ads_color', 'default' );
+	$above_footer_ad = get_option( '_newspack_ads_placement_global_above_footer' );
```
Comment (miguelpeixe) [inline newspack-theme/inc/template-functions.php:218]:
```suggestion
	$above_footer_ad      = method_exists( 'Newspack_Ads\Placements', 'can_display_ad_unit' ) && \Newspack_Ads\Placements::can_display_ad_unit( 'global_above_footer' );
```

The placements system provides a public method with more advanced checks to verify if the placement will render an ad unit which I believe is more suitable.

File: newspack-theme/inc/template-functions.php [hunk 2]
```diff
@@ -213,12 +213,17 @@ function newspack_body_classes( $classes ) {
...
 	if ( 'custom' === $ads_background_color ) {
 		$classes[] = 'ads-bg';
-	}
 
+		if ( str_contains( $above_footer_ad, '"enabled":true' ) ) {
```
Comment (miguelpeixe) [inline newspack-theme/inc/template-functions.php:222]:
```suggestion
		if ( true === $above_footer_ad ) {
```

The suggested method above returns a boolean value.

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
Working as described! One suggestion below:

File: newspack-theme/inc/template-functions.php (hunk 1 above)
Comment (laurelfulford) [reply newspack-theme/inc/template-functions.php]: 🙌 Awesome, thanks Miguel! I made this update in [a2e5486](https://github.com/Automattic/newspack-theme/pull/1746/commits/a2e548679d56567b2ca57d2f2880abb2490dbcb8).

**Comment by laurelfulford** [comment]
Woohoo! Thanks for the review! 🙌
