### PR TITLE
Fix remaining sticky header logo distortion

### LINKED ISSUE #1617: Logo stretched when centered with sticky header
The sticky header and logo sizing continues to cause some odd issues -- specifically, right now if you centre the logo and it's more of a horizontal shape, it can get distorted on non-AMP pages. 

I think setting the logo to be `object-fit: contain`, like it is when AMP is enabled, could be an easier way to get it working consistently across the two displays situations.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR tweaks the sticky header logo styles a bit, to prevent some odd cases of logo distortion (and are hopefully the last set of changes related to this!).

Closes #1617

I've created some fake logos based on the size/shape of logos I've recreated issues with here: https://cloudup.com/cvzeMzjEnrd

These specific logos showcase some different issues:
* [Medium example logo](https://cloudup.com/iEKZMtl3h5B)
* [Wide example logo](https://cloudup.com/iu-SdOI2H6B)
* [Small example logo](https://cloudup.com/i2kEAmdqxC1)
* [X-Small example logo](https://cloudup.com/iespwoToKnH)

### How to test the changes in this Pull Request:

1. Navigate to Customizer > Site Identity, and upload the 'Medium example logo'; make it as large as possible. 
2. Navigate to Customizer > Header Settings > Appearance, and check 'Centre Logo' and 'Sticky Header'
3. Copy-paste the following CSS into the Customizer > Custom CSS field. This will add a dotted border around the 'site branding' section of the header, to easier see where the logo is sitting relative to it:

```
.site-branding {
	outline: 1px dotted red;
}
```

4. View on the front end with and without AMP -- try scaling down the browser window and note how the logo looks at different breakpoints. This logo should be distorted on desktop-sized screens with AMP disabled, but correct as it scales down. 

image

When AMP is enabled it should be fine, but slightly off-centre in the `site-branding` area of the header:

image

5. Apply the PR and run `npm run build`.
6. Hard-refresh the page, and  repeat step #4. The logos should be the same size as they were on `master`.
7. When AMP is disabled, the logo should maintain its shape:

image

... and when AMP is enabled, the logo should be the same size, but better aligned inside of the site-branding area:

image

8. Try switching to a left-aligned logo, and make sure everything still looks good.
9. Switch the logo to "Wide example logo", and the logo alignment back to centred. 
10. Switch back to `master` and run `npm run build`. 
11. Repeat step #4 with this new logo; there should be some vertical distortion when AMP is disabled: 

image

12. Apply the PR and run `npm run build`; confirm that the logo is scaled correctly with and without AMP, at different screen sizes: 

image

13. Try switching to a left-aligned logo, and make sure everything still looks good.
14. Switch the logo to "Small example logo", and the logo alignment back to centred. 
15. Switch back to `master` and run `npm run build`. 
16. Repeat step #4 with this new logo; the distortion without AMP is pretty epic:

image

17. With AMP enabled, the logo's shape should be correct, but again it's misaligned in the site branding: 

image

18. Apply the PR and run `npm run build`; confirm that the logo is scaled correctly with and without AMP, at different screen sizes, and be centred inside of the `site-branding` section:

image

19. Try switching to a left-aligned logo, and make sure everything still looks good.
20. Switch the logo to "Small example logo", and the logo alignment back to centred. 
21. Switch back to `master` and run `npm run build`. 
22. Much like the above, non-AMP is kind of a mess:

image

23. Apply the PR and run `npm run build`; confirm that the logo is scaling correctly both with and without AMP:

image

24. Please try some other header settings -- the 'simplified subpage' header, the mobile CTA, and the short-vs-default height header, to see if you spot any issues. While I've tested and tweaked this at length, there is still a not-terrible chance you will find something I haven't 🙏 😅 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: newspack-theme/inc/logo-resizer.php [hunk 1]
```diff
@@ -135,10 +136,9 @@ function newspack_customize_logo_resize( $html ) {
 			}
 		}
 
-		@media (min-width: 1200px) {
-			.h-stk:not(.h-sub) .site-header .custom-logo {
-				max-width: ' . $sticky['width'] . 'px;
-				max-height: ' . $sticky['height'] . 'px;
+		@media (max-width: 1199px) and (min-width: 782px) {
+			.h-stk.h-cl:not(.h-sub) .site-header .custom-logo {
+				max-width: 100%;
```
Comment (miguelpeixe) [inline newspack-theme/inc/logo-resizer.php:141]: Works as described for most cases. I'm still getting stretched-out logos between `782` and `1199` viewports for small and x-small versions.

image

 Adding `width: auto;` seems to fix the issue, since `height` is the fixed value.

```suggestion
				max-width: 100%;
				width: auto;
```

**Review by miguelpeixe — CHANGES_REQUESTED** [review]

File: newspack-theme/inc/logo-resizer.php (hunk 1 above)
Comment (laurelfulford) [reply newspack-theme/inc/logo-resizer.php:141]: Thanks for testing this, @miguelpeixe (and apologies for the very late reply!) 

I can see that issue, too 🤦‍♀️ I'm not sure how I missed it, I think I must have made a last second change when working on this! 

I've added the `width: auto` and did some testing; it seemed to fix the issue for me, too, and didn't seem to introduce any others! Please let me know if you see any other issues, though!

**Review by miguelpeixe — APPROVED** [review]
All distortions appear to be resolved and the logos displays as expected!

**Comment by laurelfulford** [comment]
Thanks @miguelpeixe! 🙌
