### PR TITLE
Header: correct logo size display issues with AMP

### LINKED ISSUE #838: Header broken with AMP on smaller screens
**Describe the bug**
With AMP enabled, the site logo image is too wide, and causes a layout issue:

image

With AMP plugin deactivated, it's ok:

image

**Expected behavior**
The header, when AMP plugin is active, should look as it does with the plugin deactivated.

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

When scaling down images, AMP will size an image using `object-fit: contain`; if the image's size or max-size isn't the same aspect ratio, this will cause the image to appear centered inside of the max-width space, causing a gap on both sides. This happens when the image is scaled down for mobile, or for the subpage header. 

This PR should fix most cases; the only odd case is when a site is using the subpage header option, and have uploaded an alternative logo for the featured image beside and featured image behind posts that is not the same aspect ratio as the original logo (this is the case with MTFP). The logo won't be sized quite right -- for example, if the original is wider than the alternative version, the alternative version may be scaled down more than it needs to be. This is an odd case, and not the actual use case for that logo, so I think it's safe to fix this on a one-off basis with Custom CSS, but we can revisit and calculate a separate size for that logo if it turns into a bigger thing. 

Closes #838 

### How to test the changes in this Pull Request:

1. Set up a header with a left-aligned square logo, and turn on AMP to Transitional mode for easier testing. 
2. Under Customizer > Header Settings > Subpage Header, check 'Use simple header on subpages'.
3. View the AMP version of a page, and scale down the browser window to mobile size -- note the gap that appears on either side:

image

image

image

4. Navigate to a subpage, and note a similar issue in the scaled-down subpage header:

image

5. Apply the PR and run `npm run build`.
6. Revisit both pages, and confirm the logo spacing looks better; also confirm it's the same without AMP:

image

image

7. Test on a subpage with the featured image behind and featured image beside setting, and confirm it's displaying as expected, with and without AMP:

image

image

8. Try some other logo shapes -- horizontal and vertical -- and confirm they all display well with and without AMP:

image

image

image

image

image

image

image

image

image

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: newspack-theme/inc/logo-resizer.php [hunk 1]
```diff
@@ -128,6 +151,21 @@ function newspack_logo_resize_min_max( $short, $long, $short_max, $long_max, $pe
 	return $size;
 }
 
+/**
+ * Helper function to return smaller versionf of the logo size
```
Comment (jeffersonrabb) [inline newspack-theme/inc/logo-resizer.php:155]:
```suggestion
 * Helper function to return smaller version of the logo size
```

File: newspack-theme/inc/logo-resizer.php [hunk 2]
```diff
@@ -128,6 +151,21 @@ function newspack_logo_resize_min_max( $short, $long, $short_max, $long_max, $pe
...
+ */
```
Comment (jeffersonrabb) [inline newspack-theme/inc/logo-resizer.php:156]: Here's a few suggested changes to the function for readability and convention. Should be no change whatsoever to the functionality:

```
/**
 * Helper function to return smaller versionf of the logo size
 */
function newspack_logo_small_sizes( $width, $height, $max_width, $max_height ) {
	$size = array(
		'width'  => round( $max_height * ( $width / $height ) ),
		'height' => $max_height,
	);

	if ( $size['width'] > $max_width ) {
		$size['height'] = round( $max_width * ( $height / $width ) );
		$size['width']  = $max_width;
	}

	return $size;
}
```

File: newspack-theme/inc/logo-resizer.php (hunk 1 above)
Comment (laurelfulford) [reply newspack-theme/inc/logo-resizer.php]: Whoops, thanks! Fixed in 6133c91.

File: newspack-theme/inc/logo-resizer.php (hunk 2 above)
Comment (laurelfulford) [reply newspack-theme/inc/logo-resizer.php:156]: Ah, much nicer - thanks! Updated in c249184.

**Comment by laurelfulford** [comment]
Thanks Jeff!
